export const GET_MOVIES = "GET_MOVIES";
export const ADD_MOVIES_FAVORITE = "ADD_MOVIES_FAVORITE";
export const DELETE_MOVIES_FAVORITE = "DELETE_MOVIES_FAVORITE";
export const DETAIL_MOVIE = "DETAIL_MOVIE";
export const DELETE_ALL_FAVORITE = "DELETE_ALL_FAVORITE";